# Setup
paginate_path: "/page:num/"
permalink: pretty

title:            CodeColorist
tagline:          'Final Lullaby'
description:      'Close your eyes and I put us to sleep'
url:              https://blog.chichou.me

author:
  name:           'CodeColorist'

paginate:         6

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

links:
  twitter:     https://twitter.com/codecolorist
  GitHub:      https://github.com/chichou
  Patreon:     https://patreon.com/codecolorist

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: CodeColorist
  url: https://twitter.com/codecolorist

# Custom vars
version: 3.0.0

# Navbar page list
nav:
  - title: Archive
    url: /archive

  - title: RSS
    url: /atom.xml
