# Setup
paginate_path: "/page:num/"
permalink: pretty

title:            CodeColorist
tagline:          'Final Lullaby'
description:      'Close your eyes and I put us to sleep'
url:              https://chichou.github.io

author:
  name:           'CodeColorist'

paginate:         6

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

links:
  twitter:     https://twitter.com/codecolorist
  GitHub:      https://github.com/chichou
  Patreon:     https://patreon.com/codecolorist

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: CodeColorist
  url: https://twitter.com/codecolorist

# Custom vars
version: 3.0.0

# Navbar page list
nav:
  - title: Archive
    url: /archive

  - title: RSS
    url: /atom.xml

slides:
  - title: 'Many Birds, One Stone: Exploiting a Single SQLite Vulnerability Across Multiple Software (BlackHat USA 2017)'
    img: many-birds-one-stone.png
    url: https://speakerdeck.com/chichou/many-birds-one-stone-exploiting-a-single-sqlite-vulnerability-across-multiple-software

  - title: 'ModJack: Hijacking the macOS Kernel (HITB Ams 2019)'
    img: modjack-hijacking-macos-kernel.jpg
    url: https://speakerdeck.com/chichou/modjack-hijacking-the-macos-kernel-hitb-ams-2019

  - title: 'I Want to Break Free: Unusuall Logic Safari Sandbox Escapes (TyphoonCon 2019)'
    img: typhooncon-2019.jpg
    url: https://speakerdeck.com/chichou/i-want-to-break-free-unusual-logic-safari-sandbox-escape

  - title: 'Cross-Site Escape: Pwning macOS Safari Sandbox the Unusual Way (BlackHat EU 2020)'
    img: cross-site-escape.png
    url: https://speakerdeck.com/chichou/cross-site-escape-pwning-macos-safari-sandbox-the-unusual-way

  - title: 'macOS “非主流”逻辑提权漏洞研究'
    img: gossip-2019.jpg
    url: https://speakerdeck.com/chichou/gossip-shu-qi-xue-xiao-2019-macos-fei-zhu-liu-luo-ji-ti-quan-lou-dong-yan-jiu

  - title: 'Bifröst 揭秘：VMware Fusion REST API 漏洞分析'
    img: vmware-fusion-rest-api.jpg
    url: https://speakerdeck.com/chichou/bifrost-jie-mi-vmware-fusion-rest-api-lou-dong-fen-xi

  - title: 'See No Eval: Runtime Dynamic Code Execution in Objective-C (RWCTF 2021)'
    img: see-no-eval.jpg
    url: https://speakerdeck.com/chichou/see-no-eval-runtime-dynamic-code-execution-in-objective-c
