<<<<<<< HEAD
# Permalinks
permalink: pretty

# Setup
title: Poole
tagline: The Jekyll Butler
url: http://andrewhwanpark.github.io/dark-poole/
paginate: 1
baseurl: ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir: _sass
  style: :compressed
=======
# Setup
title: Dark Poole
url: https://getpoole.com
paginate: 1
baseurl: ""
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options
>>>>>>> master

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Mark Otto
  url: https://twitter.com/mdo
  email: markdotto@gmail.com

# Custom vars
<<<<<<< HEAD
version: 2.0.0
github:
  repo: https://github.com/poole/poole
=======
version: 3.0.0

# Navbar page list
nav:
  - title: Blog
    url: /archive

  - title: About
    url: /about

  - title: Feed
    url: /atom.xml
>>>>>>> master
